// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconBiGithub: typeof import('~icons/bi/github.svelte')['default']
  const IconBiLightning: typeof import('~icons/bi/lightning.svelte')['default']
}
